# Generated by Django 5.0.7 on 2024-09-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcart',
            name='isInCart',
            field=models.BooleanField(default=False),
        ),
    ]
